const { contextBridge, ipcRenderer } = require('electron');

const safeApi = {
  clearCacheRestart: () => ipcRenderer.invoke('app:clearCacheRestart'),
  getOfflineInfo: () => ipcRenderer.invoke('app:offlineInfo'),
  openLogs: () => ipcRenderer.invoke('app:openLogs')
};

const fullApi = {
  ...safeApi,
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: settings => ipcRenderer.invoke('settings:save', settings),
  importSettings: () => ipcRenderer.invoke('settings:import'),
  exportSettings: () => ipcRenderer.invoke('settings:export'),
  openStartupSettings: () => ipcRenderer.invoke('settings:openStartup'),
  checkUpdates: () => ipcRenderer.invoke('app:checkUpdates'),
  getUpdateState: () => ipcRenderer.invoke('app:getUpdateState'),
  installUpdate: () => ipcRenderer.invoke('app:installUpdate'),
  reloadApp: () => ipcRenderer.invoke('app:reload'),
  openHome: () => ipcRenderer.invoke('app:openHome'),
  restartApp: () => ipcRenderer.invoke('app:restart'),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('app:toggleAlwaysOnTop'),
  toggleMuted: () => ipcRenderer.invoke('app:toggleMuted'),
  showSettings: () => ipcRenderer.invoke('app:showSettings'),
  showLogs: () => ipcRenderer.invoke('app:showLogs'),
  showFeedback: () => ipcRenderer.invoke('app:showFeedback'),
  showRemoteConfig: () => ipcRenderer.invoke('app:showRemoteConfig'),
  showLicense: () => ipcRenderer.invoke('app:showLicense'),
  showReleaseNotes: () => ipcRenderer.invoke('app:showReleaseNotes'),
  showSafeMode: () => ipcRenderer.invoke('app:showSafeMode'),
  repairRestart: () => ipcRenderer.invoke('app:repairRestart'),
  disableRemoteConfigRestart: () => ipcRenderer.invoke('app:disableRemoteConfigRestart'),
  resetWindowState: () => ipcRenderer.invoke('app:resetWindowState'),
  getSafeModeInfo: () => ipcRenderer.invoke('app:safeModeInfo'),
  getHealth: () => ipcRenderer.invoke('app:health'),
  fetchRemoteConfig: () => ipcRenderer.invoke('app:remoteConfig'),
  checkLicense: () => ipcRenderer.invoke('app:license'),
  getLocalLicense: () => ipcRenderer.invoke('license:localStatus'),
  importLocalLicense: () => ipcRenderer.invoke('license:importLocal'),
  importLocalLicenseFile: filePath => ipcRenderer.invoke('license:importLocalFile', filePath),
  clearLocalLicense: () => ipcRenderer.invoke('license:clearLocal'),
  clearUniversalLicense: () => ipcRenderer.invoke('license:clearUniversal'),
  exportLicenseRequest: () => ipcRenderer.invoke('license:exportRequest'),
  getLicenseCenterInfo: () => ipcRenderer.invoke('license:centerInfo'),
  copyDeviceId: () => ipcRenderer.invoke('license:copyDeviceId'),
  copyLicenseStatus: () => ipcRenderer.invoke('license:copyStatus'),
  openLocalLicenseFolder: () => ipcRenderer.invoke('license:openLocalFolder'),
  openLicenseRequestFolder: () => ipcRenderer.invoke('license:openRequestFolder'),
  getRemoteConfigStatus: () => ipcRenderer.invoke('remoteConfig:status'),
  copyDiagnostics: () => ipcRenderer.invoke('app:copyDiagnostics'),
  exportDiagnosticsPackage: () => ipcRenderer.invoke('app:exportDiagnosticsPackage'),
  submitFeedback: value => ipcRenderer.invoke('feedback:submit', value),
  getLogs: () => ipcRenderer.invoke('app:getLogs'),
  openLogs: () => ipcRenderer.invoke('app:openLogs'),
  exportDiagnostics: () => ipcRenderer.invoke('app:exportDiagnostics'),
  finishOnboarding: () => ipcRenderer.invoke('onboarding:done'),
  markAnnouncementRead: id => ipcRenderer.invoke('announcement:read', id),
  openAnnouncementUrl: url => ipcRenderer.invoke('announcement:openUrl', url),
  getNotifications: () => ipcRenderer.invoke('notifications:list'),
  getDownloads: () => ipcRenderer.invoke('downloads:list'),
  openDownloadedFile: filePath => ipcRenderer.invoke('downloads:openFile', filePath),
  showDownloadedFile: filePath => ipcRenderer.invoke('downloads:showInFolder', filePath),
  onSettingsUpdated: callback => ipcRenderer.on('settings-updated', (event, value) => callback(value)),
  onNotificationsUpdated: callback => ipcRenderer.on('notifications-updated', (event, value) => callback(value)),
  onDownloadsUpdated: callback => ipcRenderer.on('downloads-updated', (event, value) => callback(value)),
  onUpdateStateUpdated: callback => ipcRenderer.on('update-state-updated', (event, value) => callback(value)),
  onRemoteConfigUpdated: callback => ipcRenderer.on('remote-config-updated', (event, value) => callback(value))
};

contextBridge.exposeInMainWorld('desktopApi', location.protocol === 'file:' ? fullApi : safeApi);
